siteName: 'Warden'

theme:
  primaryColor: '#0a0a0a'
  secondaryColor: '#fa3771'
  social:
    github: 'lgwillmore/warden'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'page'
      itemId: 'Installation'
    - type: 'page'
      itemId: 'ABAC Overview'
    - type: 'page'
      itemId: 'Quick Intro'
    - type: 'page'
      itemId: 'Policies'
    - type: 'page'
      itemId: 'FAQ'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

allPages:
  template: 'page'
  menu:
    - type: pageIds
      structure: nested
      order: 1

  metaComponents:
    - type: 'prism'
      languages:
        - 'kotlin'
        - 'groovy'
        - 'xml'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'