theme:
  social:
    github: 'lgwillmore/warden'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'page'
      itemId: 'ABAC Overview'
    - type: 'page'
      itemId: 'Quick Start'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'