siteName: 'Warden'
theme:
  primaryColor: '#0a0a0a'
  secondaryColor: '#fa3771'
  social:
    github: 'lgwillmore/warden'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'page'
      itemId: 'ABAC Overview'
    - type: 'page'
      itemId: 'Quick Intro'
    - type: 'page'
      itemId: 'Policies'
    - type: 'page'
      itemId: 'FAQ'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'