site:
  about:
    siteName: "Warden"
    subtitle: "Attribute Based Access Control for Kotlin"

theme:
  primaryColor: '#138539'
  social:
    github: 'lgwillmore/warden'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'page'
      itemId: 'Quick Intro'
    - type: 'page'
      itemId: 'Installation'
    - type: 'pages'
      group: 'core'
      asSubmenu: true
    - type: 'page'
      itemId: 'Ktor'
    - type: 'page'
      itemId: 'ABAC Overview'
    - type: 'page'
      itemId: 'FAQ'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Source Docs'
  legacySearch: false
  metaComponents:
    - type: orchidSearch
    - type: 'prism'
      languages:
        - 'kotlin'
        - 'groovy'
        - 'xml'

allPages:
  template: 'page'
  menu:
    - type: pageIds
      structure: nested
      order: 1


kotlindoc:
  sourceDirs:
    - './../../../../core/src/commonMain/kotlin'
  pages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'